[tool.poetry]
name = "Praxeus"
version = "0.0.1"
description = "A full fledged moderation bot."
authors = ["Salem4874"]

[tool.poetry.dependencies]
python = "^3.8"
discord = "^1.0.1"
flask = "^1.1.2"
praw = "^7.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
